/** English copy for the Leonardo landing. Spanish source copy remains the lookup key. */
export type LeoLanguage = 'es' | 'en';
export const ENGLISH: Record<string, string> = {
  'Agendar diagnóstico': 'Book a consultation',
  'Saltar al contenido': 'Skip to content',
  'Secciones del sitio': 'Site sections',
  'Trabajo': 'Work', 'Casos': 'Case studies', 'Sistema': 'Process', 'Paquetes': 'Packages',
  'Agendar': 'Book a call', 'Tus': 'Your', 'Datos': 'Data', 'Tu': 'Your', 'Contexto': 'Context', 'Tú decides': 'You decide',
  'BI fraccional · Guatemala & Estados Unidos': 'Fractional BI · Guatemala & United States',
  'De datos dispersos a': 'From scattered data to',
  'decisiones que venden': 'decisions that drive sales',
  'Tu departamento de inteligencia de negocios y automatización por una fracción de lo que cuesta un analista interno. Resultados desde la semana dos.': 'Your business intelligence and automation department for a fraction of the cost of an in-house analyst. Results from week two.',
  'Agendar diagnóstico gratuito': 'Book a free consultation', 'Ver paquetes': 'View packages',
  'días al primer dashboard': 'days to your first dashboard', 'propiedad de tus datos': 'ownership of your data',
  'contratos forzosos': 'lock-in contracts', 'Baja': 'Scroll', 'Lo que dicen los clientes': 'What clients say',
  'Portafolio': 'Portfolio', 'Lo que ya': 'Already', 'está corriendo': 'up and running',
  'Once proyectos en producción: cockpits ejecutivos, motores de reportería, automatizaciones y sitios. Capturas reales — y donde el cliente no permite compartir pantalla, va la cifra en vez de una imagen prestada.': 'Eleven projects in production: executive cockpits, reporting engines, automations and websites. Real screenshots — where a client cannot share a screen, we show the figures instead of a borrowed image.',
  'Filtrar por tipo de trabajo': 'Filter by type of work', 'Todo': 'All', 'Automatización': 'Automation',
  'Ver el portafolio completo': 'View the full portfolio', 'Casos seleccionados': 'Selected case studies',
  'Números que': 'Numbers that', 'cambiaron de mano': 'made a difference',
  'Impacto cuantificado en producción. Cada cifra salió de un sistema que sigue corriendo hoy.': 'Measured impact in production. Every figure comes from a system that is still running today.',
  'Margen protegido / año': 'Margin protected / year', 'Automoción': 'Automotive',
  'Apex Auto Group — cockpit ejecutivo multi-tienda': 'Apex Auto Group — multi-location executive cockpit',
  'Doce concesionarios y 85+ feeds DMS unificados en un solo Power BI con refresco sub-segundo.': 'Twelve dealerships and 85+ DMS feeds unified in one Power BI dashboard with sub-second refresh.',
  '85 reportes aislados, 5–7 días de retraso': '85 isolated reports, 5–7 days of delay',
  'Un cockpit único, fuga visible el mismo día': 'One cockpit, margin leakage visible the same day',
  'SLA · antes 81.2%': 'SLA · previously 81.2%', 'Operaciones': 'Operations',
  'Operador BPO — motor de reportería multi-tenant': 'Multi-client BPO — multi-tenant reporting engine',
  '33,370 registros de rendimiento a través de 14 sistemas de telefonía y CRM, reconciliados a diario.': '33,370 performance records across 14 telephony and CRM systems, reconciled daily.',
  '35 h/semana consolidando a mano': '35 hours/week consolidating manually',
  '28 h/semana devueltas a los supervisores': '28 hours/week returned to supervisors',
  'Menos tiempo · DSO −11 días': 'Less time · DSO −11 days', 'IA & Automatización': 'AI & Automation',
  'Conciliación de facturación médica': 'Medical billing reconciliation',
  'Python y Playwright recorren el portal con MFA, concilian contra el ledger y avisan por Slack.': 'Python and Playwright navigate the portal with MFA, reconcile against the ledger and notify the team via Slack.',
  '40 h/semana de conciliación manual': '40 hours/week of manual reconciliation',
  '2.5 h/semana supervisadas, cero errores de tipeo': '2.5 supervised hours/week, zero typing errors',
  'El sistema Sagepoint': 'The Sagepoint process', 'Tres pasos,': 'Three steps,', 'cero TI interno': 'no in-house IT',
  'La IA sola alucina y no conoce tu contexto local. Cada métrica que sale de aquí pasó por un consultor antes de llegar a tu pantalla.': 'AI on its own can hallucinate and does not know your local context. Every metric we deliver is reviewed by a consultant before it reaches your screen.',
  'PASO 01': 'STEP 01', 'PASO 02': 'STEP 02', 'PASO 03': 'STEP 03',
  'Levantamos la señal': 'Find the signal',
  'Auditamos tus fuentes reales —DMS, CRM, ERP, telefonía, las hojas de cálculo que nadie quiere abrir— y mapeamos dónde se pierde la información.': 'We audit your actual sources — DMS, CRM, ERP, telephony and the spreadsheets nobody wants to open — and map where information gets lost.',
  'Conectamos y validamos': 'Connect and validate',
  'Ingesta automatizada con Python, Playwright y Apps Script. Cada regla de validación corre a diario y un humano revisa lo que la máquina marca.': 'Automated ingestion with Python, Playwright and Apps Script. Every validation rule runs daily, and a person reviews what the system flags.',
  'Entregamos la decisión': 'Deliver the decision',
  'Dashboards que tu equipo entiende sin capacitación de tres semanas, con alertas que llegan a Slack o WhatsApp antes de que el problema crezca.': 'Dashboards your team understands without three weeks of training, with alerts delivered to Slack or WhatsApp before problems grow.',
  'Cómo se empieza': 'Getting started', 'Primero una': 'Start with a', 'prueba pequeña': 'small pilot',
  'No tienes que decidir hoy el proyecto completo. Se empieza por una radiografía de dos semanas, y de ahí se ve si hay con qué seguir. Todo con entregable, plazo y precio por escrito.': 'You do not need to commit to the full project today. Start with a two-week data assessment, then decide whether to go further. Deliverables, timelines and pricing are agreed in writing.',
  'Etapa 1': 'Stage 1', 'Etapa 2': 'Stage 2', 'Etapa 3': 'Stage 3', 'Por aquí se entra': 'Start here',
  'pago único': 'one-time payment', 'Radiografía de Datos': 'Data Assessment', '14 días': '14 days',
  '90 minutos': '90 minutes', 'de tu equipo · NDA antes de tocar un archivo': 'of your team’s time · NDA before accessing any file',
  'Auditamos dos de tus fuentes y te dejamos un dashboard vivo con hasta ocho KPIs, más un informe de oportunidades priorizadas y una ronda de revisiones. En catorce días sabes qué se puede automatizar y qué no.': 'We audit two of your data sources and deliver a live dashboard with up to eight KPIs, a prioritized opportunities report and one revision round. In fourteen days, you know what can be automated and what cannot.',
  'Se acredita completo al proyecto si contratas en 30 días': 'Fully credited toward your project if you proceed within 30 days',
  'Si la radiografía muestra que vale la pena': 'If the assessment shows it is worth pursuing',
  'desde · por proyecto': 'from · per project', 'Cockpit Ejecutivo': 'Executive Cockpit', 'Más elegido': 'Most popular',
  '4–6 semanas': '4–6 weeks', '4 horas': '4 hours', 'de tu equipo': 'of your team’s time',
  'Hasta cuatro fuentes integradas, hasta tres dashboards ejecutivos y un flujo de reportes automatizado que se lleva el 80% del tiempo manual. Incluye dos sesiones de capacitación, documentación y dos rondas de revisiones.': 'Up to four integrated sources, up to three executive dashboards and one automated reporting workflow that cuts manual time by 80%. Includes two training sessions, documentation and two revision rounds.',
  'No incluye data warehouse ni modelos a medida': 'Does not include a data warehouse or custom models',
  'Sala de Control': 'Control Room', '10–14 semanas': '10–14 weeks', '· alcance cerrado por escrito': '· scope agreed in writing',
  'Para operaciones multi-sistema donde el dato hay que construirlo antes de graficarlo. Data warehouse propio, portal a medida con usuarios y permisos, modelos predictivos dedicados e integraciones con tu CRM o ERP.': 'For operations spanning multiple systems where data must be assembled before it can be charted. Your own data warehouse, a custom portal with users and permissions, dedicated predictive models and CRM or ERP integrations.',
  'Cuando el proyecto termina': 'Once the project is complete', 'al mes · tres niveles': 'per month · three tiers',
  'Soporte Cercano': 'Ongoing Support',
  'Tus dashboards siguen vivos: mantenimiento, ajustes, coaching y WhatsApp prioritario. Prepago anual con dos meses de cortesía. Tres niveles según intensidad; cada uno define sus horas mensuales y no se acumulan.': 'Keep your dashboards running with maintenance, adjustments, coaching and priority WhatsApp support. Annual prepayment includes two complimentary months. Three tiers based on support needs, each with defined monthly hours that do not roll over.',
  '¿Buscas solo un sitio web o una aplicación, sin la parte de datos? También lo hacemos, aparte de esta escalera —': 'Looking for a website or app without the data work? We offer that separately too —',
  'mira el portafolio': 'see the portfolio', 'Testimonios': 'Testimonials', 'Lo dicen': 'Hear from', 'quienes firman': 'the decision-makers',
  'Citas de proyectos entregados, con la métrica que quedó del otro lado.': 'Quotes from delivered projects, alongside the results.',
  '“Ver la fuga de margen en repuestos el mismo día, no semanas después. Recuperamos más de $420,000 en el primer año.”': '“We can see parts margin leakage the same day, not weeks later. We recovered over $420,000 in the first year.”',
  'recuperados': 'recovered',
  '“Gestionar 33,000 registros y 14 sistemas era una pesadilla manual. Hoy el SLA está en 99.4% y liberamos 28 horas de supervisores por semana.”': '“Managing 33,000 records and 14 systems was a manual nightmare. Today our SLA is at 99.4%, and we have freed up 28 hours of supervisor time per week.”',
  'VP Operaciones · operador BPO multi-cliente': 'VP of Operations · multi-client BPO',
  '“Tuvo la paciencia de entender nuestras ideas antes de proponer nada. El primer dashboard funcional llegó en menos de 10 días.”': '“He took the time to understand our ideas before proposing anything. The first working dashboard arrived in under 10 days.”',
  'Coordinadora de Proyecto': 'Project Coordinator', '10 días': '10 days', 'a producción': 'to production',
  'Preguntas frecuentes': 'Frequently asked questions', 'Lo que': 'Your questions,', 'más preguntan': 'answered',
  '¿El diagnóstico inicial realmente es gratuito?': 'Is the initial consultation really free?',
  'Sí. Es una videollamada de 30 a 45 minutos donde revisamos tus fuentes de datos y te decimos qué se puede automatizar y qué no. Sales con un diagnóstico escrito aunque no contrates nada.': 'Yes. In a 30–45 minute video call, we review your data sources and explain what can be automated and what cannot. You receive a written assessment even if you do not hire us.',
  '¿Necesito un departamento de TI para esto?': 'Do I need an IT department?',
  'No. Trabajamos con las herramientas que ya tienes —Excel, Google Sheets, tu CRM, tu ERP— y nos integramos como tu equipo de datos externo. Si hace falta infraestructura nueva, lo decimos antes de empezar y va cotizado aparte.': 'No. We work with the tools you already use — Excel, Google Sheets, your CRM and ERP — as your external data team. If new infrastructure is needed, we discuss it before starting and quote it separately.',
  '¿De quién son los datos y los dashboards?': 'Who owns the data and dashboards?',
  'Tuyos, al 100%. Todo se construye en tus cuentas, con tus licencias. Firmamos NDA antes de tocar cualquier archivo y te entregamos la documentación completa al cierre del proyecto.': 'You do, 100%. Everything is built in your accounts with your licenses. We sign an NDA before accessing any file and provide full documentation at the end of the project.',
  '¿Qué pasa si el alcance crece a mitad del proyecto?': 'What if the scope grows during the project?',
  'Cada paquete define entregables, plazos y exclusiones por escrito antes de arrancar. Si aparece algo fuera de alcance, se cotiza como adición y decides tú — nunca se factura una sorpresa.': 'Each package defines deliverables, timelines and exclusions in writing before we start. Anything outside that scope is quoted separately for your approval — no surprise charges.',
  'Hablemos': 'Let’s talk', 'de tus datos': 'about your data',
  'Treinta minutos, sin compromiso. Traes tus fuentes y te decimos qué se puede automatizar esta misma quincena.': 'Thirty minutes, no obligation. Bring your data sources and we will explain what can be automated within the next two weeks.',
  'Escribir por WhatsApp': 'Message us on WhatsApp', 'Videollamada de 30–45 min': '30–45 minute video call',
  'Diagnóstico escrito aunque no contrates': 'Written assessment even if you do not hire us',
  'NDA antes de tocar un archivo': 'NDA before accessing any file', 'Sin contratos forzosos': 'No lock-in contracts',
  'Inteligencia de negocios y automatización para empresas en crecimiento. Guatemala y Estados Unidos.': 'Business intelligence and automation for growing companies. Guatemala and the United States.',
  'Servicios': 'Services', 'Automatización web': 'Web automation', 'Automatización en Excel': 'Excel automation',
  'Modelos predictivos': 'Predictive models', 'Compañía': 'Company', 'Contacto': 'Contact',
  'Guatemala & Estados Unidos': 'Guatemala & United States',
  'Cerrar': 'Close', 'Solicitud enviada': 'Request sent',
  'Listo. Te escribimos en menos de 24 horas.': 'All set. We will contact you within 24 hours.',
  'Revisamos lo que nos contaste y llegamos con una recomendación concreta. Si prefieres adelantar, escríbenos por WhatsApp y seguimos ahí.': 'We will review what you shared and come back with a concrete recommendation. To get started sooner, message us on WhatsApp.',
  'Diagnóstico gratuito': 'Free consultation', 'Treinta minutos, sin compromiso': 'Thirty minutes, no obligation',
  'Déjanos cómo contactarte y qué quieres resolver. NDA antes de tocar un archivo.': 'Tell us how to reach you and what you want to solve. NDA before accessing any file.',
  'Nombre': 'Name', 'Correo de trabajo': 'Work email', 'País': 'Country', 'Selecciona': 'Select',
  'Me interesa': 'I am interested in', 'Cuéntanos el contexto': 'Tell us about your situation',
  'Qué fuentes tienes, qué reporte te está costando tiempo, qué te gustaría ver.': 'Which data sources do you use, which report takes too much time, and what would you like to see?',
  'No se pudo enviar. Intenta de nuevo o escríbenos por': 'Could not send your request. Try again or message us on',
  'o escríbenos por WhatsApp': 'or message us on WhatsApp',
  'Necesitamos tu nombre.': 'Please enter your name.', 'Revisa el correo.': 'Please check your email address.',
  'Enviando…': 'Sending…', 'Agendar mi diagnóstico': 'Book my consultation',
  'Diagnóstico gratuito / consultoría general': 'Free consultation / general advice',
  'Radiografía de Datos ($750)': 'Data Assessment ($750)',
  'Cockpit Ejecutivo (desde $2,500)': 'Executive Cockpit (from $2,500)',
  'Sala de Control (desde $12,000)': 'Control Room (from $12,000)',
  'Soporte Cercano ($300+ / mes)': 'Ongoing Support ($300+ / month)',
  'Panamá': 'Panama', 'México': 'Mexico', 'Estados Unidos': 'United States', 'Otro': 'Other',
  'Diagnóstico para:': 'Consultation for:',
  'Apex Auto Group — cockpit ejecutivo en Power BI': 'Apex Auto Group — executive cockpit in Power BI',
  'Dashboard de Power BI de Apex Auto Group con unidades vendidas, ingreso neto y margen bruto por región': 'Apex Auto Group Power BI dashboard showing units sold, net revenue and gross margin by region',
  'JKS — CRM empresarial': 'JKS — enterprise CRM',
  'Pantalla de análisis y reportes del CRM empresarial de JKS con asignaciones por agente': 'JKS enterprise CRM analytics and reporting screen with assignments by agent',
  'filas reconciliadas · 79 semanas': 'rows reconciled · 79 weeks', 'Motor de reportería multi-tenant': 'Multi-tenant reporting engine',
  'Catorce sistemas de telefonía y CRM consolidados a diario. El cumplimiento de SLA pasó de 81.2% a 99.4% y liberó 28 horas de supervisión por semana.': 'Fourteen telephony and CRM systems consolidated daily. SLA compliance rose from 81.2% to 99.4%, freeing up 28 hours of supervisor time per week.',
  'Dicoma S.A. — sitio corporativo': 'Dicoma S.A. — corporate website',
  'Página de inicio de Dicoma S.A., empresa de diseño y construcción eléctrica': 'Homepage for Dicoma S.A., an electrical design and construction company',
  'GravityClaw — consola Mission Control': 'GravityClaw — Mission Control console',
  'Consola Mission Control de GravityClaw con estado del bot, tareas y actividad reciente': 'GravityClaw Mission Control console showing bot status, tasks and recent activity',
  'Operador de facturación médica (EE. UU.)': 'Medical billing operator (US)', 'menos tiempo · DSO −11 días': 'less time · DSO −11 days',
  'Python y Playwright recorren el portal con MFA, concilian contra el ledger y avisan por Slack. De 40 a 2.5 horas por semana, sin errores de tipeo.': 'Python and Playwright navigate the portal with MFA, reconcile against the ledger and send Slack notifications. From 40 to 2.5 hours per week, with no typing errors.',
  'Saludable — Nutricionista Maylin Sic': 'Saludable — Nutritionist Maylin Sic',
  'Página de inicio del sitio de nutrición Saludable con agenda de consultas': 'Saludable nutrition website homepage with appointment booking',
  'Zendesk Talk · reportería': 'Zendesk Talk · reporting', 'call units · 0 diferencias': 'call units · 0 discrepancies',
  'Cuadre entre Explore y la API': 'Reconciliation between Explore and the API',
  'Un workflow en Apps Script sustituyó la exportación manual y validó cada unidad contra las dos fuentes. El cierre pasó de horas a una corrida diaria.': 'An Apps Script workflow replaced manual exports and validated every unit against both sources. Closing went from hours of work to one daily run.',
  "Página de inicio de Jen's Desserts con pedidos por WhatsApp": "Jen's Desserts homepage with WhatsApp ordering",
  'Portal de facturación médica': 'Medical billing portal', 'eClinicalWorks · sin métricas aún': 'eClinicalWorks · no metrics yet',
  'Automatización de alertas eClinicalWorks': 'eClinicalWorks alert automation',
  'Seguimiento de alertas desde Slack, lookup de credenciales en el portal y rotación asistida de contraseñas. En construcción; sin métricas todavía.': 'Alert monitoring from Slack, portal credential lookup and assisted password rotation. Under construction; no metrics yet.',
  'Catálogo de videos de InMotion Dance Academy con filtros por estilo y nivel': 'InMotion Dance Academy video catalog with filters by style and level',
  'Ver la fuga de margen en repuestos el mismo día, no semanas después.': 'See parts margin leakage the same day, not weeks later.',
  'Hoy el SLA está en 99.4% y liberamos 28 horas de supervisores por semana.': 'Today our SLA is at 99.4%, and we have freed up 28 hours of supervisor time per week.',
  'Tuvo la paciencia de entender nuestras ideas antes de proponer nada.': 'He took the time to understand our ideas before proposing anything.',
  'Pasamos de 40 a 2.5 horas semanales de conciliación.': 'We went from 40 to 2.5 hours of reconciliation per week.',
  'Dir. de Facturación · operador de facturación médica (EE. UU.)': 'Billing Director · medical billing operator (US)',
  'Un solo cockpit para 12 concesionarios y 85 feeds de DMS.': 'One cockpit for 12 dealerships and 85 DMS feeds.',
  'Gestionar 33,000 registros y 14 sistemas era una pesadilla manual.': 'Managing 33,000 records and 14 systems was a manual nightmare.',
  'Recortamos 11 días de DSO y eliminamos los errores de tipeo.': 'We cut DSO by 11 days and eliminated typing errors.',
  'El primer dashboard funcional llegó en menos de 10 días.': 'The first working dashboard arrived in under 10 days.',
};

export function translateLeo(language: LeoLanguage, text: string): string {
  return language === 'en' ? (ENGLISH[text] ?? text) : text;
}
